apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-platform-api-data-concatenation-rmq-kube
  name: data-platform-api-data-concatenation-rmq-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-platform-api-data-concatenation-rmq-kube
      app: ORDERS
  template:
    metadata:
      labels:
        run: data-platform-api-data-concatenation-rmq-kube
        app: ORDERS
    spec:
      hostname: data-platform-api-data-concatenation-rmq-kube
      containers:
        - name: data-platform-api-data-concatenation-rmq-kube
          image: latonaio/data-platform-api-data-concatenation-rmq-kube
          imagePullPolicy: Always
          env:
            - name : "RMQ_QUEUE_FROM"
              value: "data-platform-api-data-concatenation-queue"
            - name : "RMQ_QUEUE_TO"
              value: "data-platform-api-data-concatenation-queue"
            - name: "MYSQL_DB_NAME"
              value: "DataPlatformCommonSettingsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: data-platform-api-data-concatenation-rmq-kube
  name: data-platform-api-data-concatenation-rmq-kube
spec:
  selector:
    run: data-platform-api-data-concatenation-rmq-kube
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30909
